sanghyuk2/Aim_To_Platinum

황인혁/백트래킹(Backtracking)/BOJ_10971_외판원순회2.java
황인혁/백트래킹(Backtracking)/BOJ_13771_N과M(11).java
황인혁/백트래킹(Backtracking)/BOJ_16987_계란으로계란치기.java
황인혁/백트래킹(Backtracking)/BOJ_17136_색종이붙이기.java
황인혁/백트래킹(Backtracking)/BOJ_9663_NQueen.java

```markdown
* [O] 🔖 라벨은 등록했는가? `backtracking`
```
* 
*

[황인혁] Week1_Backtracking

---

엄수혁/백트래킹(Backtracking)/BOJ_10971_외판원순회.java
엄수혁/백트래킹(Backtracking)/BOJ_13771_N과M(11).java
엄수혁/백트래킹(Backtracking)/BOJ_15665_N과M(11).java
엄수혁/백트래킹(Backtracking)/BOJ_9663_N-Queen.java

```markdown
```
* 다음주엔 더 많은 문제를 !!
*

[엄수혁] Week1_Backtracking

---

이다인/분할 정복(Divide and Conquer)/BOJ_1074_Z.py
이다인/분할 정복(Divide and Conquer)/BOJ_1992_쿼드트리.py
이다인/분할 정복(Divide and Conquer)/BOJ_2448_별찍기-11.py
이다인/분할 정복(Divide and Conquer)/BOJ_2630_색종이만들기.java
이다인/분할 정복(Divide and Conquer)/BOJ_2630_색종이만들기.py

```markdown
* [O] 👀 자신의 코드를 완벽히 이해했는가?
* [O] 🔖 라벨은 등록했는가? ex. `backtracking`, `tree`, `dp`
```
* 
*

[이다인] Week2_Divide_and_Conquer

---

엄수혁/분할 정복(Divide and Conquer)/BOJ_17829_222폴링.java
엄수혁/분할 정복(Divide and Conquer)/BOJ_18222_투에모스문자열.java
엄수혁/분할 정복(Divide and Conquer)/BOJ_2448_별찍기11.java
엄수혁/분할 정복(Divide and Conquer)/BOJ_2630_색종이만들기.java

[엄수혁] Week2_Divide_and_Conquer

---

이상혁/분할 정복(Divide&Conquer)/BOJ_17829_222-풀링.java
이상혁/분할 정복(Divide&Conquer)/BOJ_1992_쿼드트리.java
이상혁/분할 정복(Divide&Conquer)/BOJ_2448_별찍기11.java
이상혁/분할 정복(Divide&Conquer)/BOJ_2630_색종이만들기.java

[이상혁] Week2_Divide_and_Conquer 

---

황인혁/README.md
황인혁/동적 계획법(DP)/BOJ_1106_호텔.java
황인혁/동적 계획법(DP)/BOJ_2294_동전2.java
황인혁/동적 계획법(DP)/BOJ_2579_계단오르기.java
황인혁/동적 계획법(DP)/BOJ_2839_설탕배달.java

[황인혁] Week3_DP

---

이상혁/README.md
이상혁/동적 계획법(Dynamic Programming)/BOJ_2294_동전2.java
이상혁/동적 계획법(Dynamic Programming)/BOJ_2579_계단오르기.java
이상혁/동적 계획법(Dynamic Programming)/BOJ_2839_설탕배달.java

[이상혁] Week3_DP

---

이다인/README.md
이다인/동적 계획법2(Dynamic Programming)/BOJ_12865_평범한배낭.py
이다인/동적 계획법2(Dynamic Programming)/BOJ_14567_선수과목.py
이다인/동적 계획법2(Dynamic Programming)/BOJ_1520_내리막길.py
이다인/동적 계획법2(Dynamic Programming)/BOJ_15724_주지수.java
이다인/동적 계획법2(Dynamic Programming)/BOJ_15724_주지수.py

[이다인] Week4_DP

---

이상혁/동적 계획법(Dynamic Programming)/BOJ_1106_호텔.java
이상혁/동적 계획법(Dynamic Programming)/BOJ_11727_2xn_타일링_2.java
이상혁/동적 계획법2(Dynamic Programming)/BOJ_12865_평범한배낭.java
이상혁/동적 계획법2(Dynamic Programming)/BOJ_14567_선수과목(Prerequisite).java
이상혁/동적 계획법2(Dynamic Programming)/BOJ_15724_주지수.java
이상혁/동적 계획법2(Dynamic Programming)/BOJ_5557_1학년.java

* [] 🙆🏻 주석 내용을 이해하기 쉽고 정확하게 작성하였는가?
```
* 
*

[이상혁] Week4_DP

---

황인혁/README.md
황인혁/탐욕법(Greedy)/BOJ_20115_에너지_드링크.java
황인혁/탐욕법(Greedy)/BOJ_20300_서강근육맨.java
황인혁/탐욕법(Greedy)/BOJ_21758_꿀_따기.java
황인혁/탐욕법(Greedy)/BOJ_2812_크게_만들기.java

[황인혁] Week5_Greedy

---

엄수혁/README.md
엄수혁/탐욕법(Greedy)/BOJ_11399_ATM.java
엄수혁/탐욕법(Greedy)/BOJ_16953_A-B.java
엄수혁/탐욕법(Greedy)/BOJ_20115_에너지 드링크.java
엄수혁/탐욕법(Greedy)/BOJ_20300_서강근육맨.java
엄수혁/탐욕법(Greedy)/BOJ_2812_크게_만들기.java

[엄수혁] Week5_Greedy

---

이상혁/탐욕법(Greedy)/BOJ_11000_강의실_배정.java
이상혁/탐욕법(Greedy)/BOJ_11399_ATM.java
이상혁/탐욕법(Greedy)/BOJ_16953_A→B.java
이상혁/탐욕법(Greedy)/BOJ_20115_에너지_드링크.java
이상혁/탐욕법(Greedy)/BOJ_20300_서강근육맨.java
이상혁/탐욕법(Greedy)/BOJ_2812_크게_만들기.java

[이상혁] Week5_Greedy

---

황인혁/README.md
황인혁/최단 경로(Dijkstra)/BOJ_11403_경로_찾기.java
황인혁/최단 경로(Dijkstra)/BOJ_18352_특정_거리의_도시_찾기.java
황인혁/최단 경로(Dijkstra)/BOJ_1865_웜홀.java
황인혁/최단 경로(Dijkstra)/BOJ_1956_운동.java

[황인혁] Week6_Dijkstra

---

정은기/README.md
정은기/최단 경로(Dijkstra)/BOJ_11265_끝나지_않는_파티.java
정은기/최단 경로(Dijkstra)/BOJ_11403_경로_찾기.java
정은기/최단 경로(Dijkstra)/BOJ_11404_플로이드.java
정은기/최단 경로(Dijkstra)/BOJ_1956_운동.java

[정은기] Week6_Dijkstra

---

이다인/README.md
이다인/최단 경로(Dijkstra)/BOJ_11265_끝나지_않는_파티.py
이다인/최단 경로(Dijkstra)/BOJ_11403_경로_찾기.java
이다인/최단 경로(Dijkstra)/BOJ_11403_경로_찾기.py
이다인/최단 경로(Dijkstra)/BOJ_11657_타임머신.py
이다인/최단 경로(Dijkstra)/BOJ_1956_운동.java
이다인/최단 경로(Dijkstra)/BOJ_1956_운동.py

[이다인] Week6_Dijkstra

---

이상혁/최단 경로(Dijkstra)/BOJ_11403_경로_찾기.java
이상혁/최단 경로(Dijkstra)/BOJ_18352_특정_거리의_도시_찾기.java
이상혁/최단 경로(Dijkstra)/BOJ_1956_운동.java

* [] 📚 충분한 리팩토링을 거쳤는가?
```
* 
*

[이상혁] Week6_Dijkstra

---

황인혁/README.md
황인혁/트리(Tree)/BOJ_11725_트리의_부모_찾기.java
황인혁/트리(Tree)/BOJ_1991_트리_순회.java
황인혁/트리(Tree)/BOJ_2263_트리의_순회.java
황인혁/트리(Tree)/BOJ_3584_가장_가까운_공통_조상.java

[황인혁] Week7_Tree

---

이다인/README.md
이다인/트리(Tree)/BOJ_1967_트리의_지름.py
이다인/트리(Tree)/BOJ_1991_트리_순회.java
이다인/트리(Tree)/BOJ_1991_트리_순회.py
이다인/트리(Tree)/BOJ_3584_가장_가까운_공통_조상.java
이다인/트리(Tree)/BOJ_3584_가장_가까운_공통_조상.py
이다인/트리(Tree)/BOJ_5639_이진_검색_트리.py

* 
* 1967번 트리의 지름
> * https://lmcoa15.tistory.com/56
> * https://blog.myungwoo.kr/112

[이다인] Week7_Tree

---

이상혁/트리(Tree)/BOJ_11725_트리의_부모_찾기.java
이상혁/트리(Tree)/BOJ_1991_트리_순회.java
이상혁/트리(Tree)/BOJ_3584_가장_가까운_공통_조상.java
이상혁/트리(Tree)/BOJ_5639_이진_검색_트리.java

```
* Tree 문제 제출
* https://www.crocus.co.kr/660
* https://4legs-study.tistory.com/121
* https://johoonday.tistory.com/233

[이상혁] Week7_Tree

---

정은기/README.md
정은기/트리(Tree)/BOJ_11725_트리의_부모_찾기.java
정은기/트리(Tree)/BOJ_14675_단절점과_단절선.java
정은기/트리(Tree)/BOJ_1991_트리_순회.java
정은기/트리(Tree)/BOJ_3584_가장_가까운_공통_조상.java

[정은기] Week7_Tree

---

이다인/README.md
이다인/동적 계획법2(Dynamic Programming)/BOJ_5557_1학년.py
이다인/분할 정복(Divide and Conquer)/BOJ_17829_222-풀링.py
이다인/최단 경로(Dijkstra)/BOJ_1238_파티.py
이다인/탐욕법(Greedy)/BOJ_20115_에너지_드링크.py

[이다인] Week8_Review

---

정은기/README.md
정은기/최단 경로(Dijkstra)/BOJ_1238_파티.java
정은기/최단 경로(Dijkstra)/BOJ_14938_서강_그라운드.java
정은기/최단 경로(Dijkstra)/BOJ_1753_최단경로.java
정은기/최단 경로(Dijkstra)/BOJ_18352_특정_거리의_도시_찾기.java
정은기/최단 경로(Dijkstra)/BOJ_1916_최소비용_구하기.java
정은기/탐욕법(Greedy)/BOJ_11000_강의실_배정.java

* 
* <a href="https://steady-coding.tistory.com/106">1238번 파티 ref<a>

[정은기] Week8_Review

---

이상혁/동적 계획법(Dynamic Programming)/BOJ_11053_가장 긴 증가하는 부분 수열.java
이상혁/동적 계획법(Dynamic Programming)/BOJ_11055_가장 긴 증가하는 부분 수열.java
이상혁/동적 계획법(Dynamic Programming)/BOJ_2565_전깃줄.java
이상혁/동적 계획법(Dynamic Programming)/BOJ_9095_1, 2, 3 더하기.java
이상혁/이분 탐색(Binary Search)/BOJ_10815_숫자 카드.java
이상혁/이분 탐색(Binary Search)/BOJ_1789_수들의 합.java
이상혁/이분 탐색(Binary Search)/BOJ_2417_정수 제곱근.java
이상혁/이분 탐색(Binary Search)/BOJ_2565_전깃줄.java
이상혁/이분 탐색(Binary Search)/BOJ_2805_나무 자르기.java

[이상혁] Week9_Binary_Search

---

정은기/README.md
정은기/이분 탐색(Binary Search)/BOJ_13397_구간_나누기.java
정은기/이분 탐색(Binary Search)/BOJ_1477_휴게소_세우기.java
정은기/이분 탐색(Binary Search)/BOJ_1654_랜선_자르기.java
정은기/이분 탐색(Binary Search)/BOJ_2805_나무_자르기.java

[정은기] Week9_Binary_Search

---

이상혁/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_1012_유기농 배추.java
이상혁/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_11724_연결 요소의 개수.java
이상혁/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_1260_DFS와 BFS.java
이상혁/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_2178_미로 탐색.java
이상혁/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_2606_바이러스.java
이상혁/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_2667_단지번호붙이기.java

[이상혁] Week10_DFS&BFS

---

이다인/README.md
이다인/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_11559_Puyo_Puyo.java
이다인/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_11559_Puyo_Puyo.py
이다인/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_1987_알파벳.py
이다인/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_2178_미로_탐색.py
이다인/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_7569_토마토.py

[이다인] Week10_DFS&BFS

---

정은기/README.md
정은기/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_1012_유기농_배추.java
정은기/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_11559_Puyo_Puyo.java
정은기/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_11724_연결_요소의_개수.java
정은기/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_1260_DFS와_BFS.java
정은기/백준/깊이 & 너비 우선 탐색 (DFS & BFS)/BOJ_2178_미로_탐색.java

[정은기] Week10_DFS&BFS

---

정은기/README.md
정은기/백준/구현(Implementation)/BOJ_17413_단어_뒤집기.java
정은기/백준/구현(Implementation)/BOJ_20164_홀수_홀릭_호석.java
정은기/백준/구현(Implementation)/BOJ_20291_파일_정리.java
정은기/백준/구현(Implementation)/BOJ_20546_기적의_매매법.java

[정은기] Week11_Implementation
